sudo: required

language: generic

services:
  - docker

before_install: 
  - echo "start creating an image with dockerfile"
  - docker build -t kdu9303/docker-react-app-test -f Dockerfile.dev .

script: 
  - docker run -e CI=true kdu9303/docker-react-app-test npm run test -- --coverage

after_success: 
  - echo "Test Success"
