sudo: required

language: generic

services:
  - docker

before_install: 
  - echo "start creating an image with dockerfile"
  - docker build -t kdu9303/docker-react-app-test -f Dockerfile.dev .

script: 
  - docker run -e CI=true kdu9303/docker-react-app-test npm run test -- --coverage

after_success: 
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucker_name: "elasticbeanstalk-ap-northeast-2-052447275543"
  buker_path: "docker-react-app"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY